---
title: "Potential Factors of Decreasing Birth Rates in the US since the Great Recession and Beyond"
subtitle: "Reproduction of 'The Puzzle of Falling US Birth Rates since the Great Recession'(Kearney, Levine & Pardue, 2022)"
author: 
  - Chay Park
thanks: "Code and data are available at: https://github.com/Chay-HyunminPark/Social-Science-Study."
date: today
date-format: long
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(palmerpenguins)
```


# Introduction


# Data {#sec-data}

## Source
### Trend in US Birth Rates

# Load necessary libraries
library(ggplot2)

# Read the data from CSV file
data <- read.csv("fig_1.csv")

# Plotting the data
ggplot(data, aes(x = year, y = brate_all)) +
  geom_line(color = "blue") +
  geom_vline(xintercept = 2007, linetype = "dotted") +
  labs(x = "Year", y = "Births per 1,000 women age 15-44",
       title = "Birth Rates per 1,000 Women Age 15-44 Over Time",
       subtitle = "Source: CDC Vital Statistics Births Reports (2015, 2019, 2020)",
       caption = "Trend in US Birth Rates") +
  theme_minimal()


## Methodology

## Features

### Data Cleaning

### Data Modification

### Data Visualization


# Results
The results section should convey findings.
## Table, graph, table, graph

# Discussion

In the discussion section, and any other relevant section, please be sure to discuss ethics and bias, with reference to relevant literature.

## Findings

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this. 

## Ethical Implication

## Accounting for bias

## Limitation

## Future Research
